# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.1.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'
    feedsToUse: 'select'
    versioningScheme: 'off'
    arguments: '-c release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'
    arguments: '--collect "Code coverage"'
    testRunTitle: 'L0/L1'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: BuildQualityChecks@5
  inputs:
    checkCoverage: true
    coverageFailOption: 'fixed'
    coverageType: 'lines'
    coverageThreshold: '84'

- task: CopyFiles@2
  condition: ne(variables['Build.Reason'], 'PullRequest')
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src/CoveragePublisher.Console/bin/release/netcoreapp2.1'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  condition: ne(variables['Build.Reason'], 'PullRequest')
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src/CoveragePublisher.Console/bin/release/net461'
    Contents: |
      CoveragePublisher.Console.exe
      CoveragePublisher.Console.exe.config

    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PowerShell@2
  condition: ne(variables['Build.Reason'], 'PullRequest')
  inputs:
    targetType: 'inline'
    script: 'ls $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  condition: ne(variables['Build.Reason'], 'PullRequest')
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'CoveragePublisher'
    publishLocation: 'Container'
